language: java

jdk: openjdk15

sudo: false

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      quaresma_08@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
  - CODECOV_TOKEN="ae24aecb-d2e7-4706-8d24-a94b61af6c67"